export const AppString = {
  INPUT_FIELDS_NOT_FOUND: "all input fields are required",
  PASSWORD_NOT_FOUND: "password is required",
  PASSWORD_INCORRECT: "password is incorrect",
  EMAIL_USERNAME_NOT_FOUND: "email or password is required",
  AVATAR_NOT_FOUND: "avatar image is required",
  COVERIMG_NOT_FOUND: "avatar image is required",
  USER_ALREADY_EXIST: "user already exist with this email or username",
  USER_NOT_EXIST: "user not exist with this email or username",
  USER_REGISTERED: "user registered successfully",
  USER_LOGIN: "user login successfully",
  UNAUTHORIZED: "user is not authorized",
  USER_UPDATED: "user updated successfully",
  USER_LOGOUT: "user logout successfully",
  USER_RETRIEVED: "user retrieved successfully",
  PASSWORD_UPDATED: "password updated successfully",

  INVALID_SESSION: "your session is not valid",
  USER_NOT_FOUND: "user not found",
  INVALID_TOKEN: "token is invalid",
  TOKEN_EXPIRE: "session expire",

  VIDEO_UPLOADED: "video uploaded successfully",
  TITLE_DESC_REQUIRED: "title and description required",
  VIDEO_THUMBNAIL_REQUIRED: "video and thumbnail required",
  VIDEO_NOT_FOUND: "video not found",
  VIDEO_DELETED: "video deleted successfully",
  VIDEO_RETRIEVED: "video retrieved successfully",
  VIDEO_UPDATED: "video updated successfully",

  UPDATE_FAILED: "update failed !! Please try again",
  DELETE_FAILED: "delete failed !! Please try again",

  FILE_UPLOAD_ERR: "file upload error, please try again",
};
